import {
  Profile,
  Course,
  ChallengeDay,
  Achievement,
  NotificationItem,
  LeaderboardItem,
  Group,
} from '../types';

export const MOTIVATIONAL_QUOTES = [
  "“Bugungi 1% harakat ertangi katta natijaga olib keladi.”",
  "“Bilim — inson hayotidagi eng ishonchli va kuchli investitsiya.”",
  "“Bugun test yech, darsni o'zlashtir — ertaga natijangni ko'r!”",
  "“O'rganishdan to'xtagan kishi, yoshidan qat'i nazar, keksayadi.”",
  "“Katta marralar kichik va doimiy qadamlardan boshlanadi.”",
  "“Har bir xato — yangi bilim va kelajakdagi g'alaba uchun darsdir.”",
];

export const DEMO_STUDENT: Profile = {
  id: 'student-demo',
  role: 'student',
  first_name: 'Muhammadyusuf',
  last_name: 'Ahathanov',
  phone: '+998901234567',
  email: 'ahathanovmuhammadyusuf@gmail.com',
  avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  created_at: new Date(Date.now() - 30 * 24 * 3600000).toISOString(),
  group_id: 'group-1',
  group_name: 'IT-101 (Python & Web Dasturlash)',
  teacher_name: 'Dilshod Rahimov',
  level: 'Junior',
  xp: 740,
  next_level_xp: 1000,
  streak: 5,
  study_hours: 18.5,
  completed_courses: 3,
  completed_tests: 12,
  average_score: 87,
};

export const DEMO_TEACHER: Profile = {
  id: 'teacher-1',
  role: 'teacher',
  first_name: 'Dilshod',
  last_name: 'Rahimov',
  phone: '+998901112233',
  email: 'dilshod.rahimov@ilmhub.uz',
  avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
  created_at: new Date(Date.now() - 90 * 24 * 3600000).toISOString(),
  group_id: 'group-1',
  group_name: 'IT-101',
  level: 'Master',
  xp: 4500,
  next_level_xp: 5000,
  streak: 24,
  study_hours: 140,
  completed_courses: 5,
  completed_tests: 45,
  average_score: 94,
};

export const DEMO_ADMIN: Profile = {
  id: 'admin-1',
  role: 'admin',
  first_name: 'Super',
  last_name: 'Administrator',
  phone: '+998990000001',
  email: 'admin@ilmhub.uz',
  avatar_url: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80',
  created_at: new Date(Date.now() - 180 * 24 * 3600000).toISOString(),
  level: 'Master',
  xp: 9999,
  next_level_xp: 10000,
  streak: 45,
  study_hours: 320,
  completed_courses: 8,
  completed_tests: 120,
  average_score: 98,
};

export const INITIAL_CHALLENGE_DAYS: ChallengeDay[] = [
  {
    day_num: 1,
    day_name: 'Dushanba',
    task_title: 'Dasturlash asoslari testi',
    task_type: 'test',
    xp_reward: 100,
    is_completed: true,
    is_current: false,
  },
  {
    day_num: 2,
    day_name: 'Seshanba',
    task_title: 'Python o‘zgaruvchilar darsi',
    task_type: 'lesson',
    xp_reward: 80,
    is_completed: true,
    is_current: false,
  },
  {
    day_num: 3,
    day_name: 'Chorshanba',
    task_title: '10 ta algoritmik savol',
    task_type: 'questions',
    xp_reward: 120,
    is_completed: true,
    is_current: false,
  },
  {
    day_num: 4,
    day_name: 'Payshanba',
    task_title: 'Mantiqiy mini test',
    task_type: 'minitest',
    xp_reward: 90,
    is_completed: true,
    is_current: false,
  },
  {
    day_num: 5,
    day_name: 'Juma',
    task_title: 'Dars + Amaliy test',
    task_type: 'test',
    xp_reward: 150,
    is_completed: false,
    is_current: true,
  },
  {
    day_num: 6,
    day_name: 'Shanba',
    task_title: 'Qiyin kiberxavfsizlik testi',
    task_type: 'test',
    xp_reward: 200,
    is_completed: false,
    is_current: false,
  },
  {
    day_num: 7,
    day_name: 'Yakshanba',
    task_title: 'Katta Final Imtihon Testi',
    task_type: 'final',
    xp_reward: 300,
    is_completed: false,
    is_current: false,
  },
];

export const INITIAL_COURSES: Course[] = [
  {
    id: 'course-python',
    title: 'Python Dasturlash Asoslari',
    category: 'Backend & Data',
    description: 'Noldan boshlab murakkab algoritmlar, ma’lumotlar tuzilmasi va OOP tamoyillari.',
    teacher_name: 'Dilshod Rahimov',
    teacher_avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    lessons_count: 8,
    duration_hours: 14,
    level: 'Junior',
    progress: 78,
    icon: '🐍',
    banner_color: 'from-blue-600 via-indigo-600 to-cyan-500',
    tests_count: 4,
    enrolled_count: 248,
    lessons: [
      {
        id: 'py-1',
        course_id: 'course-python',
        title: '1-dars: Python nima? Sintaksis va o‘zgaruvchilar',
        duration_minutes: 25,
        order_num: 1,
        is_completed: true,
        content_text: 'Python tili sintaksisi juda sodda va o‘qish oson. Ushbu darsda biz int, float, string turlarini va o‘zgaruvchilarni e’lon qilishni ko‘rib chiqamiz.',
        key_takeaways: [
          'Python interpretatsiya qilinadigan kuchli dasturlash tilidir.',
          'O‘zgaruvchilar dinamik tipizatsiyaga ega (int, str, bool, float).',
          'Sintaksis qat’iy bo‘sh joylar (indentation) bilan belgilanadi.',
        ],
      },
      {
        id: 'py-2',
        course_id: 'course-python',
        title: '2-dars: Shartli operatorlar (if, elif, else)',
        duration_minutes: 30,
        order_num: 2,
        is_completed: true,
        content_text: 'Mantiqiy shartlar orqali dastur oqimini boshqarish. Tenglik va mantiqiy operatorlar: and, or, not.',
        key_takeaways: [
          'if-elif-else mantiqiy tarmoqlanishlarni hosil qiladi.',
          'Shartlar rost (True) yoki yolg‘on (False) qiymat qaytaradi.',
        ],
      },
      {
        id: 'py-3',
        course_id: 'course-python',
        title: '3-dars: Sikllar (for, while) va ro‘yxatlar (lists)',
        duration_minutes: 40,
        order_num: 3,
        is_completed: true,
        content_text: 'Massivlar bilan ishlash, append, pop, sort metodlari va for sikli yordamida elementlar bo‘ylab aylanish.',
        key_takeaways: [
          'List (ro‘yxat) o‘zgaruvchan (mutable) ketma-ketlikdir.',
          'for sikli iteratsiya qilinuvchi ob’ektlar bo‘ylab harakatlanadi.',
        ],
      },
      {
        id: 'py-4',
        course_id: 'course-python',
        title: '4-dars: Funksiyalar (def) va parametrlar',
        duration_minutes: 35,
        order_num: 4,
        is_completed: false,
        content_text: 'Kodni qayta ishlatish uchun funksiyalar yaratish. return operatori, ixtiyoriy argumentlar va *args, **kwargs tushunchasi.',
        key_takeaways: [
          'def kalit so‘zi yangi funksiya e’lon qiladi.',
          'Funksiya natijasini return orqali qaytarish zarur.',
        ],
      },
      {
        id: 'py-5',
        course_id: 'course-python',
        title: '5-dars: Lug‘atlar (Dictionary) va To‘plamlar (Set)',
        duration_minutes: 30,
        order_num: 5,
        is_completed: false,
        content_text: 'Kalit-qiymat (Key-Value) juftliklari bilan ishlash va unikal elementlar to‘plami.',
        key_takeaways: ['Lug‘atlar tezkor qidiruv O(1) imkonini beradi.'],
      },
    ],
  },
  {
    id: 'course-frontend',
    title: 'Zamonaviy Frontend: React & TypeScript',
    category: 'Web Dasturlash',
    description: 'Component-driven arxitektura, Tailwind CSS, Hooks va responsive zamonaviy web ilovalar.',
    teacher_name: 'Jasur Alimov',
    teacher_avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    lessons_count: 10,
    duration_hours: 18,
    level: 'Intermediate',
    progress: 50,
    icon: '💻',
    banner_color: 'from-violet-600 via-purple-600 to-indigo-700',
    tests_count: 5,
    enrolled_count: 312,
    lessons: [
      {
        id: 'fe-1',
        course_id: 'course-frontend',
        title: '1-dars: React va Virtual DOM arxitekturasi',
        duration_minutes: 20,
        order_num: 1,
        is_completed: true,
        content_text: 'React nima uchun yaratilgan va JSX qanday ishlaydi.',
        key_takeaways: ['JSX — bu JavaScript ichidagi HTML sintaksisidir.'],
      },
      {
        id: 'fe-2',
        course_id: 'course-frontend',
        title: '2-dars: useState va useEffect hooklari',
        duration_minutes: 35,
        order_num: 2,
        is_completed: true,
        content_text: 'Component holatini boshqarish va lifecycle hodisalarini ushlash.',
        key_takeaways: ['useState re-render chaqiradi, useEffect esa side-effectlarni boshqaradi.'],
      },
      {
        id: 'fe-3',
        course_id: 'course-frontend',
        title: '3-dars: Tailwind CSS bilan zamonaviy dizayn',
        duration_minutes: 30,
        order_num: 3,
        is_completed: false,
        content_text: 'Utility-first CSS, responsive break-pointlar va qorong‘u rejim.',
        key_takeaways: ['Tailwind tezkor va ortiqcha CSS fayllarsiz ishlash imkonini beradi.'],
      },
    ],
  },
  {
    id: 'course-robotics',
    title: 'Robototexnika va Arduino Dasturlash',
    category: 'Muhandislik',
    description: 'Datchiklar, motorlar, mikrokontrollerlar va aqlli uy tizimlarini qurish.',
    teacher_name: 'Nigora Saidova',
    teacher_avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    lessons_count: 6,
    duration_hours: 10,
    level: 'Beginner',
    progress: 25,
    icon: '🤖',
    banner_color: 'from-cyan-600 via-teal-600 to-emerald-600',
    tests_count: 3,
    enrolled_count: 145,
    lessons: [
      {
        id: 'rob-1',
        course_id: 'course-robotics',
        title: '1-dars: Arduino Uno platasi va elektronika asoslari',
        duration_minutes: 25,
        order_num: 1,
        is_completed: true,
        content_text: 'Pinlar, analog va raqamli signallar, rezistorlar va svetodiodlar.',
        key_takeaways: ['Arduino ochiq manbali mikrokontroller hisoblanadi.'],
      },
    ],
  },
  {
    id: 'course-it-literacy',
    title: 'Kompyuter Savodxonligi & Kiberxavfsizlik',
    category: 'IT Baza',
    description: 'Kompyuter tuzilishi, operatsion tizimlar, internet xavfsizligi va parollar himoyasi.',
    teacher_name: 'Dilshod Rahimov',
    lessons_count: 5,
    duration_hours: 8,
    level: 'Starter',
    progress: 100,
    icon: '🧠',
    banner_color: 'from-emerald-600 via-green-600 to-teal-700',
    tests_count: 3,
    enrolled_count: 420,
    lessons: [
      {
        id: 'it-1',
        course_id: 'course-it-literacy',
        title: '1-dars: Zamonaviy kompyuter qismlari va periferiya',
        duration_minutes: 20,
        order_num: 1,
        is_completed: true,
        content_text: 'Protsessor, operativ xotira, doimiy xotira va anakarta.',
        key_takeaways: ['CPU - kompyuter miyasi, RAM - vaqtinchalik xotira.'],
      },
    ],
  },
  {
    id: 'course-design',
    title: 'Grafik Dizayn & UI/UX Asoslari',
    category: 'Dizayn',
    description: 'Figma, ranglar nazariyasi, tipografika va foydalanuvchi interfeysini loyihalash.',
    teacher_name: 'Jasur Alimov',
    lessons_count: 7,
    duration_hours: 12,
    level: 'Junior',
    progress: 35,
    icon: '🎨',
    banner_color: 'from-pink-600 via-rose-600 to-orange-500',
    tests_count: 2,
    enrolled_count: 180,
    lessons: [
      {
        id: 'des-1',
        course_id: 'course-design',
        title: '1-dars: UI va UX farqi. Dizayn tamoyillari',
        duration_minutes: 30,
        order_num: 1,
        is_completed: true,
        content_text: 'Foydalanuvchi tajribasi (UX) va vizual interfeys (UI) arxitekturasi.',
        key_takeaways: ['Yaxshi dizayn foydalanuvchiga muammoni tez hal qilishda yordam beradi.'],
      },
    ],
  },
];

export const INITIAL_ACHIEVEMENTS: Achievement[] = [
  {
    id: 'ach-1',
    title: 'Birinchi Sinov',
    description: 'Platformada ilk testni muvaffaqiyatli yakunlash',
    icon: '🏆',
    xp_bonus: 50,
    is_unlocked: true,
    category: 'test',
    unlocked_at: '2026-09-15',
  },
  {
    id: 'ach-2',
    title: '5 Kunlik Olov (Streak)',
    description: 'Ketma-ket 5 kun davomida dars va testlarda qatnashish',
    icon: '🔥',
    xp_bonus: 150,
    is_unlocked: true,
    category: 'streak',
    unlocked_at: '2026-10-02',
  },
  {
    id: 'ach-3',
    title: '100% Mukammal Natija',
    description: 'Birorta ham xatosiz test topshirish (20/20 ball)',
    icon: '💯',
    xp_bonus: 200,
    is_unlocked: true,
    category: 'score',
    unlocked_at: '2026-09-28',
  },
  {
    id: 'ach-4',
    title: '10 ta Test Saralash',
    description: 'Kamida 10 ta turli testni muvaffaqiyatli topshirish',
    icon: '📚',
    xp_bonus: 250,
    is_unlocked: true,
    category: 'test',
    unlocked_at: '2026-10-01',
  },
  {
    id: 'ach-5',
    title: 'Tezkor Bilimdon',
    description: '20 ta savolli testni 10 daqiqadan kam vaqtda 90%+ ball bilan yechish',
    icon: '⚡',
    xp_bonus: 180,
    is_unlocked: true,
    category: 'score',
    unlocked_at: '2026-09-22',
  },
  {
    id: 'ach-6',
    title: 'A’lochi Talaba (90%+)',
    description: 'Kamida 5 ta testda 90% dan yuqori natija ko‘rsatish',
    icon: '🎯',
    xp_bonus: 220,
    is_unlocked: true,
    category: 'score',
    unlocked_at: '2026-09-30',
  },
  {
    id: 'ach-7',
    title: '7 Kunlik Challenge G‘olibi',
    description: 'Haftalik 7 kunlik marafonni to‘liq yakunlash',
    icon: '👑',
    xp_bonus: 300,
    is_unlocked: false,
    progress: 4,
    max_progress: 7,
    category: 'streak',
  },
  {
    id: 'ach-8',
    title: 'Python Magistri',
    description: 'Python kursining barcha darslari va testlarini yakunlash',
    icon: '🐍',
    xp_bonus: 400,
    is_unlocked: false,
    progress: 3,
    max_progress: 5,
    category: 'mastery',
  },
  {
    id: 'ach-9',
    title: 'Junior Darajasi',
    description: 'Kamida 500 XP to‘plab Junior unvonini qo‘lga kiritish',
    icon: '🚀',
    xp_bonus: 100,
    is_unlocked: true,
    category: 'mastery',
    unlocked_at: '2026-09-20',
  },
  {
    id: 'ach-10',
    title: 'Intermediate Darajasi',
    description: '1000 XP to‘plab Intermediate bosqichiga yetishish',
    icon: '💎',
    xp_bonus: 300,
    is_unlocked: false,
    progress: 740,
    max_progress: 1000,
    category: 'mastery',
  },
  {
    id: 'ach-11',
    title: 'Mantiq Dahosi',
    description: 'Barcha algoritmik va mantiqiy savollarga to‘g‘ri javob berish',
    icon: '💡',
    xp_bonus: 150,
    is_unlocked: true,
    category: 'score',
  },
  {
    id: 'ach-12',
    title: 'Faol O‘quvchi',
    description: 'Platformada 20 soatdan ko‘proq vaqt ta’lim olish',
    icon: '⏱',
    xp_bonus: 150,
    is_unlocked: false,
    progress: 18,
    max_progress: 20,
    category: 'mastery',
  },
  {
    id: 'ach-13',
    title: 'Kiber Himoyachi',
    description: 'Kiberxavfsizlik bo‘yicha testda 95%+ natija olish',
    icon: '🛡',
    xp_bonus: 200,
    is_unlocked: true,
    category: 'test',
  },
  {
    id: 'ach-14',
    title: 'Guruh Yetakchisi (Top 1)',
    description: 'O‘z guruhi reytingida 1-o‘rinni egallash',
    icon: '🥇',
    xp_bonus: 350,
    is_unlocked: true,
    category: 'streak',
  },
  {
    id: 'ach-15',
    title: 'Front-End Ustasi',
    description: 'React va TypeScript bo‘yicha 3 ta amaliy testni topshirish',
    icon: '💻',
    xp_bonus: 250,
    is_unlocked: false,
    progress: 2,
    max_progress: 3,
    category: 'mastery',
  },
  {
    id: 'ach-16',
    title: 'Tungi Izlanuvchi',
    description: 'Kechki payt soat 22:00 dan keyin dars o‘qish yoki test ishlash',
    icon: '🌙',
    xp_bonus: 80,
    is_unlocked: true,
    category: 'streak',
  },
  {
    id: 'ach-17',
    title: 'Ertalabki Ziyo',
    description: 'Ertalab soat 08:00 gacha faol bo‘lish',
    icon: '☀️',
    xp_bonus: 80,
    is_unlocked: false,
    category: 'streak',
  },
  {
    id: 'ach-18',
    title: 'Master Darajasi',
    description: 'Platformada eng oliy — Master darajasiga ko‘tarilish (5000+ XP)',
    icon: '👑',
    xp_bonus: 1000,
    is_unlocked: false,
    progress: 740,
    max_progress: 5000,
    category: 'mastery',
  },
  {
    id: 'ach-19',
    title: 'Robototexnika Ishqibozi',
    description: 'Arduino kursining ilk modulini muvaffaqiyatli yakunlash',
    icon: '⚙️',
    xp_bonus: 120,
    is_unlocked: true,
    category: 'test',
  },
  {
    id: 'ach-20',
    title: 'ILMHUB Diplomi',
    description: '3 ta rasmiy kurs va ularning yakuniy imtihonlarini topshirish',
    icon: '🎓',
    xp_bonus: 500,
    is_unlocked: false,
    progress: 1,
    max_progress: 3,
    category: 'mastery',
  },
];

export const INITIAL_LEADERBOARD: LeaderboardItem[] = [
  {
    rank: 1,
    user_id: 'student-demo',
    name: 'Muhammadyusuf Ahathanov',
    avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    group_name: 'IT-101',
    level: 'Junior',
    xp: 1420,
    streak: 6,
    tests_count: 14,
    average_score: 91,
    is_current_user: true,
  },
  {
    rank: 2,
    user_id: 'student-2',
    name: 'Malika Yusupova',
    avatar_url: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    group_name: 'Frontend-01',
    level: 'Intermediate',
    xp: 1380,
    streak: 5,
    tests_count: 13,
    average_score: 89,
  },
  {
    rank: 3,
    user_id: 'student-1',
    name: 'Aziz Karimov',
    avatar_url: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80',
    group_name: 'IT-101',
    level: 'Junior',
    xp: 1250,
    streak: 4,
    tests_count: 11,
    average_score: 85,
  },
  {
    rank: 4,
    user_id: 'student-5',
    name: 'Bobur Mirzayev',
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    group_name: 'Python Beginner',
    level: 'Junior',
    xp: 1190,
    streak: 7,
    tests_count: 12,
    average_score: 87,
  },
  {
    rank: 5,
    user_id: 'student-4',
    name: 'Zuhra Ahmedova',
    avatar_url: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&auto=format&fit=crop&q=80',
    group_name: 'Robototexnika',
    level: 'Starter',
    xp: 1080,
    streak: 3,
    tests_count: 9,
    average_score: 83,
  },
  {
    rank: 6,
    user_id: 'student-7',
    name: 'Sardor Bekchanov',
    avatar_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    group_name: 'IT-101',
    level: 'Starter',
    xp: 950,
    streak: 2,
    tests_count: 8,
    average_score: 79,
  },
  {
    rank: 7,
    user_id: 'student-8',
    name: 'Madina Shodiyeva',
    avatar_url: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    group_name: 'Frontend-01',
    level: 'Starter',
    xp: 910,
    streak: 4,
    tests_count: 8,
    average_score: 84,
  },
  {
    rank: 8,
    user_id: 'student-9',
    name: 'Farrux Ganiyev',
    avatar_url: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
    group_name: 'Robototexnika',
    level: 'Beginner',
    xp: 840,
    streak: 1,
    tests_count: 7,
    average_score: 77,
  },
  {
    rank: 9,
    user_id: 'student-10',
    name: 'Shahlo Saidova',
    avatar_url: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    group_name: 'Matematika',
    level: 'Beginner',
    xp: 780,
    streak: 3,
    tests_count: 6,
    average_score: 81,
  },
  {
    rank: 10,
    user_id: 'student-3',
    name: 'Jasur Nazarov',
    avatar_url: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80',
    group_name: 'IT-101',
    level: 'Beginner',
    xp: 720,
    streak: 2,
    tests_count: 6,
    average_score: 75,
  },
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-1',
    title: 'Yangi test qo‘shildi!',
    message: '“Umumiy Intellekt va Mantiq Testi (20 ta savol)” sizning guruhingiz uchun ochildi.',
    type: 'test',
    time: '5 daqiqa oldin',
    read: false,
  },
  {
    id: 'notif-2',
    title: '🔥 5 kunlik streak saqlandi!',
    message: 'Ajoyib natija! Ertaga ham o‘qishni davom ettiring va yangi bonus XP oling.',
    type: 'streak',
    time: '2 soat oldin',
    read: false,
  },
  {
    id: 'notif-3',
    title: '🏆 Yangi achievement ochildi',
    message: '“Tezkor Bilimdon” yutug‘iga erishdingiz (+180 XP qo‘shildi).',
    type: 'achievement',
    time: 'Kecha',
    read: true,
  },
  {
    id: 'notif-4',
    title: '📚 Yangi dars yuklandi',
    message: 'Python Dasturlash kursiga 4-dars: Funksiyalar va return operatori qo‘shildi.',
    type: 'course',
    time: '2 kun oldin',
    read: true,
  },
];

export const LEVEL_THRESHOLDS = {
  Beginner: { min: 0, max: 250, badge: '🌱' },
  Starter: { min: 250, max: 500, badge: '⚡' },
  Junior: { min: 500, max: 1000, badge: '🚀' },
  Intermediate: { min: 1000, max: 2000, badge: '💎' },
  Advanced: { min: 2000, max: 3500, badge: '🔥' },
  Expert: { min: 3500, max: 5000, badge: '🧠' },
  Master: { min: 5000, max: 10000, badge: '👑' },
};
